/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/pokedex': RouteRecordInfo<'/pokedex', '/pokedex', Record<never, never>, Record<never, never>>,
    '/pokedex/': RouteRecordInfo<'/pokedex/', '/pokedex', Record<never, never>, Record<never, never>>,
    '/pokedex/create': RouteRecordInfo<'/pokedex/create', '/pokedex/create', Record<never, never>, Record<never, never>>,
    '/pokedex/edit': RouteRecordInfo<'/pokedex/edit', '/pokedex/edit', Record<never, never>, Record<never, never>>,
    '/pokedex/edit/[id]': RouteRecordInfo<'/pokedex/edit/[id]', '/pokedex/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/pokedex/view/[id]': RouteRecordInfo<'/pokedex/view/[id]', '/pokedex/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
